# Generated by Django 4.2.6 on 2023-11-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleView', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(verbose_name='Дата проведения'),
        ),
    ]
